version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run compile
      - run: npm run test